### PR TITLE
allow laravel 5.4

### PR DESCRIPTION
**Pull request by tomschlick**

### CODE REVIEW

**Comment by percymamedy** [comment]
Thanks, I was planning on implementing that but currently facing some issues with ```orchestra/testbench :3.4.x``` when using Laravel 5.4 while running Unit tests.

https://travis-ci.org/percymamedy/laravel-dev-booter/jobs/197068146

I think I need to update PHPUnit in require-dev or remove it completely and let orchestra/testbench decide what version to use.

Would be great if you could help me there.

**Comment by tomschlick** [comment]
Trying that now to see if it works...

**Comment by tomschlick** [comment]
That didn't work... I'll just update it to ~5.0 which should bring it in line with orchestra/testbench

**Comment by percymamedy** [comment]
I guess this could work ```"phpunit/phpunit": "~4.0|~5.0"```

**Comment by percymamedy** [comment]
Could you replace the following line :

```php
$app->make('Illuminate\Foundation\Bootstrap\ConfigureLogging')->bootstrap($app);
```

with this one

```php
if ($app->version() >= 5.3 && $app->version() < 5.4) {
    $app->make('Illuminate\Foundation\Bootstrap\ConfigureLogging')->bootstrap($app);
}
```

in file ```tests/RegistrationTest.php``` in ```createApplication``` method

I think this should do the trick.


Thanks.

**Comment by tomschlick** [comment]
That seemed to do it 👍

**Comment by percymamedy** [comment]
Cool.. Thanks !!... I will merge and make a new release for Laravel 5.4 support....

**Pull request merged**
